export const REGISTER_PROGRESS = "REGISTER_PROGRESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";
export const LOGIN_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAILED = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
